import sys
sys.path.insert(0, '.')
from scripts.writer import write

# reports/index.html
reports_html = '''{% extends "base.html" %}

{% block content %}
<div class="page-header">
    <div>
        <h1 class="page-title">Executive Reporting Center</h1>
        <div class="page-subtitle">Generate and export executive network intelligence, security compliance, and usage summaries</div>
    </div>
    <div>
        <button id="btn-gen-report" class="btn btn-primary btn-sm">+ Generate Daily Summary</button>
    </div>
</div>

<div class="card">
    <div class="data-table-container">
        <table class="data-table">
            <thead>
                <tr>
                    <th>Report Title</th>
                    <th>Type</th>
                    <th>Format</th>
                    <th>Generated By</th>
                    <th>Created At</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="tbody-reports">
                <tr><td colspan="6" style="text-align:center; padding:2rem;">Loading reports archive...</td></tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="module">
    import { HttpClient } from '/static/js/core/http.js';
    import { Toast } from '/static/js/components/toast.js';

    async function loadReports() {
        try {
            const res = await HttpClient.get('/api/v1/reports');
            const items = res.data;
            const tbody = document.getElementById('tbody-reports');

            if (items.length === 0) {
                tbody.innerHTML = '<tr><td colspan="6" style="text-align:center; padding:2rem; color:var(--text-muted);">No reports generated yet.</td></tr>';
                return;
            }

            tbody.innerHTML = items.map(r => `
                <tr>
                    <td style="font-weight:600; color:var(--text-primary);">${r.title}</td>
                    <td><span class="badge badge-low">${r.report_type}</span></td>
                    <td><code>${r.format}</code></td>
                    <td>${r.generated_by}</td>
                    <td>${r.created_at ? r.created_at.substring(0, 19).replace('T', ' ') : 'Just now'}</td>
                    <td><button class="btn btn-secondary btn-sm btn-download-rep">Download</button></td>
                </tr>
            `).join('');

            document.querySelectorAll('.btn-download-rep').forEach(b => {
                b.addEventListener('click', () => Toast.success('Report downloaded to storage.'));
            });
        } catch (err) {
            Toast.error('Failed to load reports.');
        }
    }

    document.getElementById('btn-gen-report').addEventListener('click', async () => {
        try {
            const res = await HttpClient.post('/api/v1/reports/generate');
            Toast.success(res.message);
            loadReports();
        } catch (err) {
            Toast.error('Generation failed.');
        }
    });

    loadReports();
</script>
{% endblock %}
'''
write('app/templates/reports/index.html', reports_html)

# audit/index.html
audit_html = '''{% extends "base.html" %}

{% block content %}
<div class="page-header">
    <div>
        <h1 class="page-title">Tamper-Proof Audit Trail & Ledger</h1>
        <div class="page-subtitle">Cryptographically chained HMAC-SHA256 audit ledger verifying system integrity</div>
    </div>
    <div>
        <button id="btn-verify-audit" class="btn btn-primary btn-sm">🔒 Verify Ledger Integrity</button>
    </div>
</div>

<div class="card">
    <div class="data-table-container">
        <table class="data-table">
            <thead>
                <tr>
                    <th>Action</th>
                    <th>User</th>
                    <th>Resource</th>
                    <th>Status</th>
                    <th>Entry HMAC Hash</th>
                    <th>Timestamp</th>
                </tr>
            </thead>
            <tbody id="tbody-audit">
                <tr><td colspan="6" style="text-align:center; padding:2rem;">Loading audit logs...</td></tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="module">
    import { HttpClient } from '/static/js/core/http.js';
    import { Toast } from '/static/js/components/toast.js';

    async function loadAudit() {
        try {
            const res = await HttpClient.get('/api/v1/audit-logs');
            const items = res.data.items;
            const tbody = document.getElementById('tbody-audit');

            if (items.length === 0) {
                tbody.innerHTML = '<tr><td colspan="6" style="text-align:center; padding:2rem; color:var(--text-muted);">No audit entries found.</td></tr>';
                return;
            }

            tbody.innerHTML = items.map(l => `
                <tr>
                    <td style="font-weight:600; color:var(--text-primary); font-family:var(--font-mono);">${l.action}</td>
                    <td>${l.username}</td>
                    <td><code>${l.resource_type || 'System'}</code></td>
                    <td><span class="badge badge-${l.status === 'SUCCESS' ? 'optimal' : 'critical'}">${l.status}</span></td>
                    <td><code style="font-size:0.75rem; color:var(--accent-cyan);">${l.entry_hash ? l.entry_hash.substring(0, 16) + '...' : 'GENESIS'}</code></td>
                    <td>${l.timestamp ? l.timestamp.substring(0, 19).replace('T', ' ') : 'N/A'}</td>
                </tr>
            `).join('');
        } catch (err) {
            Toast.error('Failed to load audit trail.');
        }
    }

    document.getElementById('btn-verify-audit').addEventListener('click', async () => {
        try {
            const res = await HttpClient.get('/api/v1/audit-logs/verify');
            if (res.data.is_tamper_free) {
                Toast.success(`Audit chain verified 100% intact (${res.data.verified_records} records verified).`);
            } else {
                Toast.error('Audit chain tamper detected!');
            }
        } catch (err) {
            Toast.error('Verification failed.');
        }
    });

    loadAudit();
</script>
{% endblock %}
'''
write('app/templates/audit/index.html', audit_html)

# users/index.html
users_html = '''{% extends "base.html" %}

{% block content %}
<div class="page-header">
    <div>
        <h1 class="page-title">User & Access Management</h1>
        <div class="page-subtitle">Role-based access control (RBAC), security analysts, and administrator accounts</div>
    </div>
</div>

<div class="card">
    <div class="data-table-container">
        <table class="data-table">
            <thead>
                <tr>
                    <th>User Name</th>
                    <th>Email Address</th>
                    <th>Primary Role</th>
                    <th>Status</th>
                    <th>MFA</th>
                </tr>
            </thead>
            <tbody id="tbody-users">
                <tr><td colspan="5" style="text-align:center; padding:2rem;">Loading enterprise directory...</td></tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="module">
    import { HttpClient } from '/static/js/core/http.js';
    import { Toast } from '/static/js/components/toast.js';

    async function loadUsers() {
        try {
            const res = await HttpClient.get('/api/v1/users');
            const items = res.data.items;
            const tbody = document.getElementById('tbody-users');

            tbody.innerHTML = items.map(u => `
                <tr>
                    <td style="font-weight:600; color:var(--text-primary);">${u.full_name} (${u.username})</td>
                    <td><code>${u.email}</code></td>
                    <td><span class="badge badge-low">${u.primary_role}</span></td>
                    <td><span class="badge badge-${u.is_active ? 'optimal' : 'critical'}">${u.is_active ? 'ACTIVE' : 'LOCKED'}</span></td>
                    <td><span class="badge badge-${u.mfa_enabled ? 'optimal' : 'medium'}">${u.mfa_enabled ? 'ENABLED' : 'DISABLED'}</span></td>
                </tr>
            `).join('');
        } catch (err) {
            Toast.error('Failed to load users.');
        }
    }
    loadUsers();
</script>
{% endblock %}
'''
write('app/templates/users/index.html', users_html)

# settings/index.html
settings_html = '''{% extends "base.html" %}

{% block content %}
<div class="page-header">
    <div>
        <h1 class="page-title">System Settings & Privacy Controls</h1>
        <div class="page-subtitle">Working shift schedules, health model weights, and strict zero-payload privacy enforcement</div>
    </div>
</div>

<div style="max-width:800px;">
    <div class="card" style="margin-bottom:1.5rem;">
        <div class="card-header">
            <div class="card-title">Enterprise Operating Hours</div>
        </div>
        <form id="form-settings">
            <div style="display:grid; grid-template-columns:1fr 1fr; gap:1.25rem; margin-bottom:1.25rem;">
                <div>
                    <label class="form-label" style="display:block; font-size:0.8rem; margin-bottom:0.35rem; color:var(--text-secondary);">Office Start Time (UTC)</label>
                    <input type="text" id="cfg-start" class="form-input" value="09:00" style="width:100%; padding:0.55rem; background:var(--bg-input); border:1px solid var(--border-color); border-radius:var(--radius-md); color:#fff;">
                </div>
                <div>
                    <label class="form-label" style="display:block; font-size:0.8rem; margin-bottom:0.35rem; color:var(--text-secondary);">Office End Time (UTC)</label>
                    <input type="text" id="cfg-end" class="form-input" value="18:00" style="width:100%; padding:0.55rem; background:var(--bg-input); border:1px solid var(--border-color); border-radius:var(--radius-md); color:#fff;">
                </div>
            </div>

            <div style="margin-bottom:1.5rem;">
                <label class="form-label" style="display:block; font-size:0.8rem; margin-bottom:0.35rem; color:var(--text-secondary);">Telemetry Retention Period (Days)</label>
                <input type="number" id="cfg-retention" class="form-input" value="90" style="width:100%; padding:0.55rem; background:var(--bg-input); border:1px solid var(--border-color); border-radius:var(--radius-md); color:#fff;">
            </div>

            <button type="submit" class="btn btn-primary btn-sm">Save Configuration</button>
        </form>
    </div>

    <!-- Privacy Card -->
    <div class="card">
        <div class="card-header">
            <div class="card-title">Zero-Payload Privacy Safeguards</div>
            <span class="badge badge-optimal">ENFORCED</span>
        </div>
        <p style="font-size:0.85rem; color:var(--text-secondary); line-height:1.6;">
            NetWatch AI platform architecture strictly prohibits packet payload logging, email inspection, keystroke recording, or private document capture. Only network layer metadata, DNS query names, IP addresses, and bandwidth bytes are recorded in accordance with enterprise IT monitoring governance.
        </p>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="module">
    import { HttpClient } from '/static/js/core/http.js';
    import { Toast } from '/static/js/components/toast.js';

    document.getElementById('form-settings').addEventListener('submit', async (e) => {
        e.preventDefault();
        try {
            await HttpClient.post('/api/v1/settings/config', {
                office_start_time: document.getElementById('cfg-start').value,
                office_end_time: document.getElementById('cfg-end').value,
                retention_days: document.getElementById('cfg-retention').value
            });
            Toast.success('Settings saved successfully.');
        } catch (err) {
            Toast.error('Failed to save settings.');
        }
    });
</script>
{% endblock %}
'''
write('app/templates/settings/index.html', settings_html)

# Error Templates
for code, title, msg in [
    (400, 'Bad Request', 'The server could not understand the requested telemetry payload.'),
    (403, 'Forbidden Access', 'You lack authorized clearance to inspect this resource.'),
    (404, 'Endpoint Not Found', 'The requested route or network asset does not exist.'),
    (500, 'Internal Server Error', 'An unexpected telemetry processor error occurred.')
]:
    err_html = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{code} -- {title}</title>
    <link rel="stylesheet" href="/static/css/app.css">
</head>
<body style="min-height:100vh; display:flex; align-items:center; justify-content:center; text-align:center;">
    <div>
        <div style="font-size:5rem; font-weight:900; color:var(--accent-cyan); font-family:var(--font-mono);">{code}</div>
        <h1 style="font-size:1.75rem; font-weight:700; color:var(--text-primary); margin-bottom:0.5rem;">{title}</h1>
        <p style="color:var(--text-secondary); max-width:400px; margin:0 auto 1.5rem;">{msg}</p>
        <a href="/dashboard" class="btn btn-primary">Return to Console ➔</a>
    </div>
</body>
</html>
'''
    write(f'app/templates/errors/{code}.html', err_html)

print('Governance (Reports, Audit, Users, Settings) and Error templates created.')
