import sys
sys.path.insert(0, '.')
from scripts.writer import write

# 1. Models (Policy, Alert, Incident)
policy_model = '''from datetime import datetime, timezone
from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship
from app.models.base import BaseModel, db
from app.constants import PolicyAction, AlertSeverity

class NetworkPolicy(BaseModel):
    \"\"\"Configurable enterprise network traffic policy.\"\"\"
    __tablename__ = 'nw_policies'

    name = Column(String(128), unique=True, nullable=False, index=True)
    description = Column(Text, nullable=True)
    category = Column(String(64), default='BANDWIDTH', nullable=False, index=True) # BANDWIDTH, DOMAIN, TIME, SECURITY
    severity = Column(String(16), default=AlertSeverity.HIGH.value, nullable=False)
    action = Column(String(32), default=PolicyAction.CREATE_INCIDENT.value, nullable=False)
    
    is_enabled = Column(Boolean, default=True, nullable=False, index=True)
    condition_json = Column(Text, nullable=False) # e.g. {'metric': 'bytes_out', 'operator': '>', 'threshold': 524288000, 'window_seconds': 300}
    created_by = Column(String(64), default='admin', nullable=False)
    violation_count = Column(Integer, default=0, nullable=False)
    last_triggered_at = Column(DateTime, nullable=True)

    violations = relationship('PolicyViolationEvent', back_populates='policy', cascade='all, delete-orphan')

class PolicyViolationEvent(BaseModel):
    \"\"\"Audit event recorded when network traffic breaches a policy.\"\"\"
    __tablename__ = 'nw_policy_violations'

    policy_id = Column(String(36), ForeignKey('nw_policies.id', ondelete='CASCADE'), nullable=False, index=True)
    device_id = Column(String(36), ForeignKey('nw_devices.id'), nullable=True, index=True)
    severity = Column(String(16), nullable=False)
    violation_details = Column(Text, nullable=False)
    observed_value = Column(String(64), nullable=True)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False, index=True)

    policy = relationship('NetworkPolicy', back_populates='violations')
    device = relationship('Device')
'''
write('app/models/policy.py', policy_model)

alert_model = '''from datetime import datetime, timezone
from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship
from app.models.base import BaseModel, db
from app.constants import AlertSeverity

class Alert(BaseModel):
    \"\"\"Atomic telemetry event alert generated by monitoring engines.\"\"\"
    __tablename__ = 'nw_alerts'

    title = Column(String(256), nullable=False, index=True)
    category = Column(String(64), default='SECURITY', nullable=False, index=True) # PERFORMANCE, SECURITY, ANOMALY, POLICY
    severity = Column(String(16), default=AlertSeverity.MEDIUM.value, nullable=False, index=True)
    
    device_id = Column(String(36), ForeignKey('nw_devices.id'), nullable=True, index=True)
    subnet_id = Column(String(36), ForeignKey('nw_subnets.id'), nullable=True, index=True)
    correlation_group_id = Column(String(36), ForeignKey('nw_alert_correlation_groups.id'), nullable=True, index=True)
    incident_id = Column(String(36), ForeignKey('nw_incidents.id'), nullable=True, index=True)
    
    source = Column(String(64), default='HealthEngine', nullable=False)
    message = Column(Text, nullable=False)
    is_acknowledged = Column(Boolean, default=False, nullable=False, index=True)
    acknowledged_by = Column(String(64), nullable=True)
    acknowledged_at = Column(DateTime, nullable=True)
    is_silenced = Column(Boolean, default=False, nullable=False)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False, index=True)

    device = relationship('Device')
    correlation_group = relationship('AlertCorrelationGroup', back_populates='alerts')
    incident = relationship('Incident', back_populates='alerts')

class AlertCorrelationGroup(BaseModel):
    \"\"\"Correlated group of alerts combined across temporal and topological windows.\"\"\"
    __tablename__ = 'nw_alert_correlation_groups'

    correlation_key = Column(String(128), unique=True, nullable=False, index=True)
    title = Column(String(256), nullable=False)
    severity = Column(String(16), default=AlertSeverity.HIGH.value, nullable=False)
    alert_count = Column(Integer, default=1, nullable=False)
    first_seen_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)
    last_seen_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False, index=True)
    is_active = Column(Boolean, default=True, nullable=False, index=True)

    alerts = relationship('Alert', back_populates='correlation_group')
'''
write('app/models/alert.py', alert_model)

incident_model = '''from datetime import datetime, timezone
from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship
from app.models.base import BaseModel, db
from app.constants import IncidentStatus, IncidentSeverity

class Incident(BaseModel):
    \"\"\"Formal enterprise network incident with investigation timeline and root-cause analysis.\"\"\"
    __tablename__ = 'nw_incidents'

    incident_number = Column(String(32), unique=True, nullable=False, index=True) # e.g. INC-2026-0042
    title = Column(String(256), nullable=False, index=True)
    summary = Column(Text, nullable=False)
    
    status = Column(String(32), default=IncidentStatus.OPEN.value, nullable=False, index=True)
    severity = Column(String(32), default=IncidentSeverity.SEV2_HIGH.value, nullable=False, index=True)
    category = Column(String(64), default='Performance Degradation', nullable=False)
    
    assigned_to = Column(String(128), nullable=True) # User email or username
    lead_investigator = Column(String(128), nullable=True)
    
    affected_device_id = Column(String(36), ForeignKey('nw_devices.id'), nullable=True, index=True)
    affected_subnet_id = Column(String(36), ForeignKey('nw_subnets.id'), nullable=True, index=True)
    
    root_cause = Column(Text, nullable=True)
    remediation_steps = Column(Text, nullable=True)
    resolution_notes = Column(Text, nullable=True)
    resolved_at = Column(DateTime, nullable=True)
    
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False, index=True)

    alerts = relationship('Alert', back_populates='incident')
    timeline_entries = relationship('IncidentTimelineEntry', back_populates='incident', cascade='all, delete-orphan', order_by='IncidentTimelineEntry.timestamp.asc()')
    evidence_items = relationship('IncidentEvidence', back_populates='incident', cascade='all, delete-orphan')

    def to_dict(self, exclude=None):
        data = super().to_dict(exclude=exclude)
        data['alert_count'] = len(self.alerts)
        data['timeline_count'] = len(self.timeline_entries)
        return data

class IncidentTimelineEntry(BaseModel):
    \"\"\"Chronological log of activities, investigation notes, and status changes in an incident.\"\"\"
    __tablename__ = 'nw_incident_timeline'

    incident_id = Column(String(36), ForeignKey('nw_incidents.id', ondelete='CASCADE'), nullable=False, index=True)
    author = Column(String(64), nullable=False)
    entry_type = Column(String(32), default='NOTE', nullable=False) # NOTE, STATUS_CHANGE, EVIDENCE_ADDED, ROOT_CAUSE_IDENTIFIED
    message = Column(Text, nullable=False)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    incident = relationship('Incident', back_populates='timeline_entries')

class IncidentEvidence(BaseModel):
    \"\"\"Attached telemetry evidence, flow dumps, or anomaly snapshots.\"\"\"
    __tablename__ = 'nw_incident_evidence'

    incident_id = Column(String(36), ForeignKey('nw_incidents.id', ondelete='CASCADE'), nullable=False, index=True)
    evidence_type = Column(String(32), default='FLOW_METRIC', nullable=False)
    title = Column(String(128), nullable=False)
    payload_json = Column(Text, nullable=False)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    incident = relationship('Incident', back_populates='evidence_items')
'''
write('app/models/incident.py', incident_model)

# 2. Repositories
policy_repo = '''from typing import List, Optional
from sqlalchemy import desc
from app.models.policy import NetworkPolicy, PolicyViolationEvent
from app.repositories.base_repository import BaseRepository
from app.models.base import db

class PolicyRepository(BaseRepository):
    def __init__(self):
        super().__init__(NetworkPolicy)

    def list_policies(self, enabled_only: bool = False) -> List[NetworkPolicy]:
        query = NetworkPolicy.query.filter_by(is_deleted=False)
        if enabled_only:
            query = query.filter_by(is_enabled=True)
        return query.order_by(desc(NetworkPolicy.created_at)).all()

    def record_violation(self, violation: PolicyViolationEvent):
        db.session.add(violation)
        # Increment policy violation counter
        policy = NetworkPolicy.query.get(violation.policy_id)
        if policy:
            policy.violation_count += 1
            import datetime
            policy.last_triggered_at = datetime.datetime.now(datetime.timezone.utc)
        db.session.commit()
        return violation
'''
write('app/repositories/policy_repository.py', policy_repo)

alert_repo = '''from typing import List, Optional, Dict, Any
from datetime import datetime, timezone, timedelta
from sqlalchemy import desc, func
from app.models.alert import Alert, AlertCorrelationGroup
from app.repositories.base_repository import BaseRepository
from app.models.base import db
from app.utils.datetime_utils import utc_now

class AlertRepository(BaseRepository):
    def __init__(self):
        super().__init__(Alert)

    def list_alerts(self, severity: str = None, category: str = None, unacknowledged_only: bool = False,
                    page: int = 1, per_page: int = 25):
        query = Alert.query.filter_by(is_deleted=False)
        if severity:
            query = query.filter_by(severity=severity)
        if category:
            query = query.filter_by(category=category)
        if unacknowledged_only:
            query = query.filter_by(is_acknowledged=False)
            
        pagination = query.order_by(desc(Alert.timestamp)).paginate(page=page, per_page=per_page, error_out=False)
        return {
            'items': pagination.items,
            'total': pagination.total,
            'page': pagination.page,
            'per_page': pagination.per_page,
            'pages': pagination.pages
        }

    def get_active_correlation_groups(self) -> List[AlertCorrelationGroup]:
        return AlertCorrelationGroup.query.filter_by(is_active=True, is_deleted=False).order_by(
            desc(AlertCorrelationGroup.last_seen_at)
        ).all()
'''
write('app/repositories/alert_repository.py', alert_repo)

incident_repo = '''from typing import List, Optional, Dict, Any
from datetime import datetime, timezone
from sqlalchemy import desc
from app.models.incident import Incident, IncidentTimelineEntry, IncidentEvidence
from app.repositories.base_repository import BaseRepository
from app.models.base import db
from app.utils.datetime_utils import utc_now

class IncidentRepository(BaseRepository):
    def __init__(self):
        super().__init__(Incident)

    def get_next_incident_number(self) -> str:
        year = utc_now().year
        count = Incident.query.count() + 1
        return f'INC-{year}-{count:04d}'

    def list_incidents(self, status: str = None, severity: str = None, page: int = 1, per_page: int = 20):
        query = Incident.query.filter_by(is_deleted=False)
        if status:
            query = query.filter_by(status=status)
        if severity:
            query = query.filter_by(severity=severity)
        pagination = query.order_by(desc(Incident.created_at)).paginate(page=page, per_page=per_page, error_out=False)
        return {
            'items': pagination.items,
            'total': pagination.total,
            'page': pagination.page,
            'per_page': pagination.per_page,
            'pages': pagination.pages
        }

    def add_timeline_entry(self, incident_id: str, author: str, entry_type: str, message: str) -> IncidentTimelineEntry:
        entry = IncidentTimelineEntry(
            incident_id=incident_id,
            author=author,
            entry_type=entry_type,
            message=message,
            timestamp=utc_now()
        )
        db.session.add(entry)
        db.session.commit()
        return entry
'''
write('app/repositories/incident_repository.py', incident_repo)

# 3. Services
policy_engine = '''import json
from typing import List, Dict, Any
from app.models.policy import NetworkPolicy, PolicyViolationEvent
from app.models.telemetry import NetworkFlowMetric, DNSQueryLog
from app.models.alert import Alert
from app.repositories.policy_repository import PolicyRepository
from app.constants import PolicyAction, AlertSeverity
from app.utils.datetime_utils import utc_now
from app.models.base import db

class PolicyExecutionEngine:
    def __init__(self, policy_repo: PolicyRepository = None):
        self.policy_repo = policy_repo or PolicyRepository()

    def evaluate_flow(self, flow: NetworkFlowMetric) -> List[PolicyViolationEvent]:
        \"\"\"Evaluates active network policies against ingested flow metric.\"\"\"
        violations = []
        policies = self.policy_repo.list_policies(enabled_only=True)

        for policy in policies:
            try:
                cond = json.loads(policy.condition_json) if isinstance(policy.condition_json, str) else policy.condition_json
            except Exception:
                continue

            metric = cond.get('metric', 'bytes_out')
            operator = cond.get('operator', '>')
            threshold = cond.get('threshold', 100_000_000)

            val = getattr(flow, metric, 0)
            triggered = False
            if operator == '>' and val > threshold:
                triggered = True
            elif operator == '>=' and val >= threshold:
                triggered = True

            if triggered:
                v = PolicyViolationEvent(
                    policy_id=policy.id,
                    device_id=flow.device_id,
                    severity=policy.severity,
                    violation_details=f'Policy \"{policy.name}\" violated: {metric}={val} {operator} {threshold}.',
                    observed_value=str(val),
                    timestamp=utc_now()
                )
                self.policy_repo.record_violation(v)
                violations.append(v)

                # Generate alert if required
                alert = Alert(
                    title=f'Policy Breach: {policy.name}',
                    category='POLICY',
                    severity=policy.severity,
                    device_id=flow.device_id,
                    subnet_id=flow.subnet_id,
                    source='PolicyEngine',
                    message=f'Device breached enterprise rule {policy.name}. Observed: {val}.',
                    timestamp=utc_now()
                )
                db.session.add(alert)
                db.session.commit()

        return violations
'''
write('app/services/policy_engine.py', policy_engine)

alert_correlation = '''from typing import List, Optional
from datetime import datetime, timezone, timedelta
from app.models.alert import Alert, AlertCorrelationGroup
from app.repositories.alert_repository import AlertRepository
from app.models.base import db
from app.utils.datetime_utils import utc_now

class AlertCorrelationEngine:
    def __init__(self, alert_repo: AlertRepository = None):
        self.alert_repo = alert_repo or AlertRepository()

    def correlate_alert(self, alert: Alert) -> Optional[AlertCorrelationGroup]:
        \"\"\"
        Correlates incoming atomic alert into existing temporal and topological correlation groups.
        Collapses alert floods (e.g. 50 simultaneous high-latency alerts on same subnet into 1 group).
        \"\"\"
        time_window = utc_now() - timedelta(minutes=15)
        
        # Build correlation key (e.g., SUBNET:192.168.1.0/24:PERFORMANCE)
        key = f'{alert.category}:{alert.subnet_id or alert.device_id or \"GLOBAL\"}'
        
        group = AlertCorrelationGroup.query.filter(
            AlertCorrelationGroup.correlation_key == key,
            AlertCorrelationGroup.last_seen_at >= time_window,
            AlertCorrelationGroup.is_active == True
        ).first()

        if group:
            group.alert_count += 1
            group.last_seen_at = utc_now()
            alert.correlation_group_id = group.id
        else:
            group = AlertCorrelationGroup(
                correlation_key=key,
                title=f'Correlated {alert.category} Incident ({alert.title})',
                severity=alert.severity,
                alert_count=1,
                first_seen_at=utc_now(),
                last_seen_at=utc_now(),
                is_active=True
            )
            db.session.add(group)
            db.session.flush()
            alert.correlation_group_id = group.id

        db.session.commit()
        return group
'''
write('app/services/alert_correlation.py', alert_correlation)

incident_service = '''from typing import Dict, Any, List, Optional
from datetime import datetime, timezone
from app.repositories.incident_repository import IncidentRepository
from app.repositories.audit_repository import AuditRepository
from app.models.incident import Incident, IncidentTimelineEntry, IncidentEvidence
from app.constants import IncidentStatus, IncidentSeverity, AuditAction
from app.utils.datetime_utils import utc_now
from app.errors.exceptions import NotFoundError, ValidationError

class IncidentManagementService:
    def __init__(self, incident_repo: IncidentRepository = None, audit_repo: AuditRepository = None):
        self.incident_repo = incident_repo or IncidentRepository()
        self.audit_repo = audit_repo or AuditRepository()

    def create_incident(self, data: Dict[str, Any], creator: str = 'admin') -> Incident:
        inc_num = self.incident_repo.get_next_incident_number()
        title = data.get('title', '').strip()
        if not title:
            raise ValidationError('Incident title is required.')

        incident = Incident(
            incident_number=inc_num,
            title=title,
            summary=data.get('summary', 'Enterprise network incident created for investigation.'),
            status=data.get('status', IncidentStatus.OPEN.value),
            severity=data.get('severity', IncidentSeverity.SEV2_HIGH.value),
            category=data.get('category', 'Network Performance'),
            assigned_to=data.get('assigned_to'),
            lead_investigator=creator,
            affected_device_id=data.get('affected_device_id'),
            affected_subnet_id=data.get('affected_subnet_id'),
            root_cause=data.get('root_cause'),
            created_at=utc_now()
        )
        created = self.incident_repo.create(incident)
        
        # Initial timeline entry
        self.incident_repo.add_timeline_entry(
            incident_id=created.id,
            author=creator,
            entry_type='STATUS_CHANGE',
            message=f'Incident {inc_num} opened with severity {created.severity}.'
        )

        self.audit_repo.log_event(
            action=AuditAction.INCIDENT_CREATED,
            resource_type='Incident',
            username=creator,
            resource_id=created.id,
            status='SUCCESS',
            details={'incident_number': inc_num, 'severity': created.severity}
        )
        return created

    def update_incident_status(self, incident_id: str, new_status: str, author: str = 'admin', notes: str = None) -> Incident:
        incident = self.incident_repo.get_by_id(incident_id)
        if not incident:
            raise NotFoundError('Incident not found.')

        old_status = incident.status
        incident.status = new_status
        if new_status in ('resolved', 'closed'):
            incident.resolved_at = utc_now()
            if notes:
                incident.resolution_notes = notes

        from app.models.base import db
        db.session.commit()

        self.incident_repo.add_timeline_entry(
            incident_id=incident.id,
            author=author,
            entry_type='STATUS_CHANGE',
            message=f'Status transitioned from {old_status.upper()} to {new_status.upper()}. {notes or \"\"}'
        )

        self.audit_repo.log_event(
            action=AuditAction.INCIDENT_STATUS_CHANGED,
            resource_type='Incident',
            username=author,
            resource_id=incident.id,
            status='SUCCESS',
            details={'from': old_status, 'to': new_status}
        )
        return incident
'''
write('app/services/incident_service.py', incident_service)

# 4. APIs for Policies, Alerts, Incidents
pol_api = '''from flask import Blueprint, request, jsonify
from app.models.policy import NetworkPolicy
from app.repositories.policy_repository import PolicyRepository
from app.middleware.auth_middleware import login_required, roles_required, get_current_user
from app.models.base import db
import json

policies_api_bp = Blueprint('policies_api', __name__, url_prefix='/api/v1/policies')
policy_repo = PolicyRepository()

@policies_api_bp.route('', methods=['GET'])
@login_required
def list_policies():
    policies = policy_repo.list_policies()
    return jsonify({
        'status': 'success',
        'data': [p.to_dict() for p in policies]
    }), 200

@policies_api_bp.route('', methods=['POST'])
@login_required
@roles_required('super_admin', 'network_admin')
def create_policy():
    data = request.get_json() or {}
    user = get_current_user()
    cond = data.get('condition_json')
    if isinstance(cond, dict):
        cond = json.dumps(cond)
        
    policy = NetworkPolicy(
        name=data['name'],
        description=data.get('description'),
        category=data.get('category', 'BANDWIDTH'),
        severity=data.get('severity', 'high'),
        action=data.get('action', 'create_incident'),
        is_enabled=bool(data.get('is_enabled', True)),
        condition_json=cond or '{\"metric\": \"bytes_out\", \"operator\": \">\", \"threshold\": 100000000}',
        created_by=user.username if user else 'admin'
    )
    db.session.add(policy)
    db.session.commit()
    return jsonify({'status': 'success', 'message': 'Policy created.', 'data': policy.to_dict()}), 201

@policies_api_bp.route('/<policy_id>/toggle', methods=['PATCH'])
@login_required
@roles_required('super_admin', 'network_admin')
def toggle_policy(policy_id):
    p = policy_repo.get_by_id(policy_id)
    if not p:
        return jsonify({'status': 'error', 'message': 'Policy not found.'}), 404
    p.is_enabled = not p.is_enabled
    db.session.commit()
    return jsonify({'status': 'success', 'message': f'Policy state set to {p.is_enabled}.', 'data': p.to_dict()}), 200
'''
write('app/routes/policies_api.py', pol_api)

alert_api = '''from flask import Blueprint, request, jsonify
from app.repositories.alert_repository import AlertRepository
from app.middleware.auth_middleware import login_required
from app.models.alert import Alert
from app.models.base import db
from app.utils.datetime_utils import utc_now

alerts_api_bp = Blueprint('alerts_api', __name__, url_prefix='/api/v1/alerts')
alert_repo = AlertRepository()

@alerts_api_bp.route('', methods=['GET'])
@login_required
def list_alerts():
    sev = request.args.get('severity')
    cat = request.args.get('category')
    page = int(request.args.get('page', 1))
    per_page = int(request.args.get('per_page', 25))
    result = alert_repo.list_alerts(severity=sev, category=cat, page=page, per_page=per_page)
    return jsonify({
        'status': 'success',
        'data': {
            'items': [a.to_dict() for a in result['items']],
            'total': result['total'],
            'page': result['page'],
            'pages': result['pages']
        }
    }), 200

@alerts_api_bp.route('/correlated', methods=['GET'])
@login_required
def list_correlated_groups():
    groups = alert_repo.get_active_correlation_groups()
    return jsonify({'status': 'success', 'data': [g.to_dict() for g in groups]}), 200

@alerts_api_bp.route('/<alert_id>/acknowledge', methods=['POST'])
@login_required
def acknowledge_alert(alert_id):
    a = alert_repo.get_by_id(alert_id)
    if not a:
        return jsonify({'status': 'error', 'message': 'Alert not found.'}), 404
    a.is_acknowledged = True
    a.acknowledged_at = utc_now()
    db.session.commit()
    return jsonify({'status': 'success', 'message': 'Alert acknowledged.'}), 200
'''
write('app/routes/alerts_api.py', alert_api)

inc_api = '''from flask import Blueprint, request, jsonify
from app.repositories.incident_repository import IncidentRepository
from app.services.incident_service import IncidentManagementService
from app.middleware.auth_middleware import login_required, roles_required, get_current_user

incidents_api_bp = Blueprint('incidents_api', __name__, url_prefix='/api/v1/incidents')
inc_repo = IncidentRepository()
inc_service = IncidentManagementService()

@incidents_api_bp.route('', methods=['GET'])
@login_required
def list_incidents():
    status = request.args.get('status')
    severity = request.args.get('severity')
    page = int(request.args.get('page', 1))
    per_page = int(request.args.get('per_page', 20))
    result = inc_repo.list_incidents(status=status, severity=severity, page=page, per_page=per_page)
    return jsonify({
        'status': 'success',
        'data': {
            'items': [i.to_dict() for i in result['items']],
            'total': result['total'],
            'page': result['page'],
            'pages': result['pages']
        }
    }), 200

@incidents_api_bp.route('/<incident_id>', methods=['GET'])
@login_required
def get_incident(incident_id):
    inc = inc_repo.get_by_id(incident_id)
    if not inc:
        return jsonify({'status': 'error', 'message': 'Incident not found.'}), 404
    data = inc.to_dict()
    data['timeline'] = [t.to_dict() for t in inc.timeline_entries]
    data['evidence'] = [e.to_dict() for e in inc.evidence_items]
    return jsonify({'status': 'success', 'data': data}), 200

@incidents_api_bp.route('', methods=['POST'])
@login_required
@roles_required('super_admin', 'network_admin', 'security_analyst')
def create_incident():
    data = request.get_json() or {}
    user = get_current_user()
    inc = inc_service.create_incident(data, creator=user.username if user else 'admin')
    return jsonify({'status': 'success', 'message': 'Incident created.', 'data': inc.to_dict()}), 201

@incidents_api_bp.route('/<incident_id>/status', methods=['PATCH'])
@login_required
@roles_required('super_admin', 'security_analyst', 'network_admin')
def update_incident_status(incident_id):
    data = request.get_json() or {}
    user = get_current_user()
    inc = inc_service.update_incident_status(
        incident_id, data.get('status', 'investigating'),
        author=user.username if user else 'admin',
        notes=data.get('notes')
    )
    return jsonify({'status': 'success', 'message': 'Incident status updated.', 'data': inc.to_dict()}), 200

@incidents_api_bp.route('/<incident_id>/timeline', methods=['POST'])
@login_required
def add_timeline_entry(incident_id):
    data = request.get_json() or {}
    user = get_current_user()
    entry = inc_repo.add_timeline_entry(
        incident_id=incident_id,
        author=user.username if user else 'admin',
        entry_type=data.get('entry_type', 'NOTE'),
        message=data.get('message', '')
    )
    return jsonify({'status': 'success', 'message': 'Timeline note added.', 'data': entry.to_dict()}), 201
'''
write('app/routes/incidents_api.py', inc_api)

print('Milestone 5 (Policies, Alerts, Incidents) successfully generated.')
