from datetime import datetime, timezone
from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship
from app.models.base import BaseModel, db
from app.constants import AlertSeverity

class Alert(BaseModel):
    """Atomic telemetry event alert generated by monitoring engines."""
    __tablename__ = 'nw_alerts'

    title = Column(String(256), nullable=False, index=True)
    category = Column(String(64), default='SECURITY', nullable=False, index=True) # PERFORMANCE, SECURITY, ANOMALY, POLICY
    severity = Column(String(16), default=AlertSeverity.MEDIUM.value, nullable=False, index=True)
    
    device_id = Column(String(36), ForeignKey('nw_devices.id'), nullable=True, index=True)
    subnet_id = Column(String(36), ForeignKey('nw_subnets.id'), nullable=True, index=True)
    correlation_group_id = Column(String(36), ForeignKey('nw_alert_correlation_groups.id'), nullable=True, index=True)
    incident_id = Column(String(36), ForeignKey('nw_incidents.id'), nullable=True, index=True)
    
    source = Column(String(64), default='HealthEngine', nullable=False)
    message = Column(Text, nullable=False)
    is_acknowledged = Column(Boolean, default=False, nullable=False, index=True)
    acknowledged_by = Column(String(64), nullable=True)
    acknowledged_at = Column(DateTime, nullable=True)
    is_silenced = Column(Boolean, default=False, nullable=False)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False, index=True)

    device = relationship('Device')
    correlation_group = relationship('AlertCorrelationGroup', back_populates='alerts')
    incident = relationship('Incident', back_populates='alerts')

class AlertCorrelationGroup(BaseModel):
    """Correlated group of alerts combined across temporal and topological windows."""
    __tablename__ = 'nw_alert_correlation_groups'

    correlation_key = Column(String(128), unique=True, nullable=False, index=True)
    title = Column(String(256), nullable=False)
    severity = Column(String(16), default=AlertSeverity.HIGH.value, nullable=False)
    alert_count = Column(Integer, default=1, nullable=False)
    first_seen_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)
    last_seen_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False, index=True)
    is_active = Column(Boolean, default=True, nullable=False, index=True)

    alerts = relationship('Alert', back_populates='correlation_group')
