from datetime import datetime, timezone
from sqlalchemy import Boolean, Column, DateTime, Float, ForeignKey, Integer, String, Text
from app.models.base import BaseModel, db

class CapacityForecast(BaseModel):
    """Bandwidth growth and capacity saturation forecasts generated by time-series models."""
    __tablename__ = 'nw_capacity_forecasts'

    target_scope = Column(String(128), default='Global Gateway Uplink', nullable=False)
    forecast_horizon_days = Column(Integer, default=30, nullable=False) # 7, 30, 90
    
    current_usage_mbps = Column(Float, default=45.0, nullable=False)
    projected_usage_mbps = Column(Float, default=65.0, nullable=False)
    capacity_limit_mbps = Column(Float, default=100.0, nullable=False)
    
    growth_rate_pct_monthly = Column(Float, default=8.5, nullable=False)
    saturation_risk_level = Column(String(16), default='MODERATE', nullable=False) # CRITICAL, HIGH, MODERATE, LOW
    estimated_saturation_date = Column(DateTime, nullable=True)
    confidence_interval_95_upper = Column(Float, default=72.0, nullable=False)
    confidence_interval_95_lower = Column(Float, default=58.0, nullable=False)
    
    recommendation = Column(Text, nullable=False)
    generated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)
